"""airbench_sign.py — M5.1/M5.2 Manifest Signing Tool

Reads the model roster YAML (which now has real artifact hashes) and:
1. Computes HMAC-SHA256 qualification signatures for each target's
   full qualification payload.
2. Computes the manifest-level HMAC-SHA256 signature over the entire
   roster (excluding the top-level `signature` field).
3. Writes a signed_patches.yaml with the computed values to paste
   into model_roster.yaml.

Usage:
    python airbench_sign.py

Architecture: No network calls. Signing key stays on local disk only.
Follows the AirBench invariant — no external services, no runtime model
calls, no file mutations to the authoritative ledger.
"""
from __future__ import annotations

import hashlib
import hmac
import json
import sys
from pathlib import Path

try:
    import yaml  # type: ignore
except ImportError:
    print("ERROR: PyYAML not installed. Run: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

ROSTER_PATH = Path("models/roster/v0/model_roster.yaml")
KEY_PATH = Path(".airbench_signing_key")
OUTPUT_PATH = Path("airbench_signed_patches.yaml")


def _canonical(obj) -> bytes:
    """Produce deterministic, compact JSON bytes for HMAC input."""
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")


def _hmac_sign(key: bytes, payload: object) -> str:
    return hmac.new(key, _canonical(payload), hashlib.sha256).hexdigest()


def build_target_qualification_payload(target: dict) -> dict:
    """Build the canonical qualification payload for a single target.

    This mirrors what ModelRegistry.load() / verify_qualification_signature()
    expects: the full target dict minus `qualification_signature`.
    """
    return {k: v for k, v in sorted(target.items()) if k != "qualification_signature"}


def main() -> None:
    if not KEY_PATH.exists():
        print(f"ERROR: Signing key not found at {KEY_PATH}", file=sys.stderr)
        print("Generate one with: python -c \"import secrets; open('.airbench_signing_key','wb').write(secrets.token_bytes(32))\"")
        sys.exit(1)

    key = KEY_PATH.read_bytes()
    if len(key) != 32:
        print(f"ERROR: Signing key must be exactly 32 bytes, got {len(key)}", file=sys.stderr)
        sys.exit(1)

    roster_text = ROSTER_PATH.read_text(encoding="utf-8")
    data = yaml.safe_load(roster_text)

    patches: list[dict] = []

    # ── Per-target qualification signatures ──────────────────────────────────
    targets = data.get("roster", {}).get("targets", [])
    for target in targets:
        tid = target.get("target_id", "unknown")
        payload = build_target_qualification_payload(target)
        sig = _hmac_sign(key, payload)
        patches.append({
            "target_id": tid,
            "field": "qualification_signature",
            "value": sig,
        })
        print(f"  {tid}: {sig}")

    # ── Manifest-level signature ──────────────────────────────────────────────
    # The manifest signature covers the entire document except `signature` itself.
    top_level_unsigned = {k: v for k, v in data.items() if k != "signature"}
    manifest_sig = _hmac_sign(key, top_level_unsigned)
    patches.append({
        "target_id": "__manifest__",
        "field": "signature",
        "value": manifest_sig,
    })
    print(f"\nmanifest signature: {manifest_sig}")

    # ── Write output ──────────────────────────────────────────────────────────
    out_lines = [
        "# airbench_signed_patches.yaml",
        "# Paste these values into model_roster.yaml",
        "# Generated by airbench_sign.py — do not commit the signing key",
        "",
        "patches:",
    ]
    for p in patches:
        out_lines.append(f"  - target_id: {p['target_id']}")
        out_lines.append(f"    field: {p['field']}")
        out_lines.append(f"    value: \"{p['value']}\"")
        out_lines.append("")

    OUTPUT_PATH.write_text("\n".join(out_lines), encoding="utf-8")
    print(f"\nPatches written to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
